#!/bin/bash

# Debug
exec 2> >(tee -a /var/log/corectrl-install.log)
exec 1>&2

# Usuário atual
currentuser=$(who | awk '{ print $1 }' | head -n 1)

# Pasta autostart
autostartfolder="$currentuser/.config/autostart"

# Checa se a pasta /home/.config/autostart existe
if [ -d $autostart ]; then
	# Se sim, copia o .desktop para o autostart
	cp /usr/share/applications/org.corectrl.corectrl.desktop $autostartfolder/org.corectrl.corectrl.desktop
	chown $currentuser:$currentuser $autostartfolder/org.corectrl.corectrl.desktop
else
	# Se não, cria a pasta e depois copia o .desktop
	mkdir -p $autostartfolder
	chown $currentuser:$currentuser $autostartfolder
	cp /usr/share/applications/org.corectrl.corectrl.desktop $autostartfolder/org.corectrl.corectrl.desktop
	chown $currentuser:$currentuser $autostartfolder/org.corectrl.corectrl.desktop
fi

# Copia as configurações do CoreCtrl
cp -R -v /tmp/corectrl/corectrl.ini /home/$currentuser/.config/corectrl/
cp -R -v /tmp/corectrl/_global_.ccpro /home/$currentuser/.config/corectrl/profiles/

# Altera as permissões
chown -R $currentuser:$currentuser /home/$currentuser/.config/corectrl
chown -R $currentuser:$currentuser /home/$currentuser/.config/corectrl/profiles

# Não vai perguntar a senha de root
sed -i 's/user/'$currentuser'/' /etc/polkit-1/localauthority/50-local.d/90-corectrl.pkla

