#!/bin/bash

# Debug
LOG_FILE=/var/log/corectrl-$(date +%Y-%m-%d_%H-%M).log
exec > >(tee -a ${LOG_FILE}) 2>&1

# Usuário atual
currentuser=$(who | awk '{ print $1 }' | head -n 1)

# Inicia o CoreCtrl na inicialização
if [[ ! -d /home/$currentuser/.config/autostart ]]
then
	mkdir -p /home/$currentuser/.config/autostart
	cp -R -v /usr/share/applications/org.corectrl.corectrl.desktop /home/$currentuser/.config/autostart/
	chown $currentuser:$currentuser /home/$currentuser/.config/autostart
	chown $currentuser:$currentuser /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
else
	if [[ ! -f /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop ]]; then
		cp -R -v /usr/share/applications/org.corectrl.corectrl.desktop /home/$currentuser/.config/autostart/
		chown $currentuser:$currentuser /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
	fi
fi

# Copia as configurações do CoreCtrl
if [[ ! -d /home/$currentuser/.config/corectrl ]]
then
	mkdir -p /home/$currentuser/.config/corectrl
	chown -R $currentuser:$currentuser /home/$currentuser/.config/corectrl
	cp -R -v /tmp/corectrl/corectrl.ini /home/$currentuser/.config/corectrl/
	chown $currentuser:$currentuser /home/$currentuser/.config/corectrl/corectrl.ini
else
	if [[ ! -f /home/$currentuser/.config/corectrl.ini ]]; then
		cp -R -v /tmp/corectrl/corectrl.ini /home/$currentuser/.config/corectrl/
		chown $currentuser:$currentuser /home/$currentuser/.config/corectrl/corectrl.ini
	fi
fi

# Não vai perguntar a senha de root
sed -i 's/user/'$currentuser'/' /etc/polkit-1/localauthority/50-local.d/90-corectrl.pkla

