#!/bin/bash

# Debug
exec 2> >(tee -a /var/log/corectrl-install.log)
exec 1>&2

# Usuário atual
currentuser=$(who | awk '{ print $1 }' | head -n 1)

# Inicia o CoreCtrl na inicialização
if [[ ! -d /home/$currentuser/.config/autostart ]]
then
	mkdir -p /home/$currentuser/.config/autostart
	cp /usr/share/applications/org.corectrl.corectrl.desktop /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
	chown $currentuser:$currentuser /home/$currentuser/.config/autostart
	chown $currentuser:$currentuser /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
else
	cp /usr/share/applications/org.corectrl.corectrl.desktop /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
	chown $currentuser:$currentuser /home/$currentuser/.config/autostart/org.corectrl.corectrl.desktop
fi

# Permissões

# Copia as configurações do CoreCtrl
mkdir -p /home/$currentuser/.config/corectrl
cp -R -v /tmp/corectrl/corectrl.ini /home/$currentuser/.config/corectrl/
mkdir -p /home/$currentuser/.config/corectrl/profiles
cp -R -v /tmp/corectrl/_global_.ccpro /home/$currentuser/.config/corectrl/profiles/

# Altera as permissões
chown -R $currentuser:$currentuser /home/$currentuser/.config/corectrl
chown -R $currentuser:$currentuser /home/$currentuser/.config/corectrl/profiles

# Não vai perguntar a senha de root
sed -i 's/user/'$currentuser'/' /etc/polkit-1/localauthority/50-local.d/90-corectrl.pkla

